### PR TITLE
fix: timezone issues caused by inconsistent API

### LINKED ISSUE #29: updateUser should send Timezone not TimeZone

### PR DESCRIPTION
**Pull request by brianreichtcs**
If approved, this PR resolved #29 which is caused by the fact that our client will pass pretty much anything along to the SmarterU API in the `Timezone` field, but `createUser` and `updateUser` expect the "Provided Name" of the timezone while `getUser` and other read API's return the "Display Value" of the timezone. This PR solves the issue by turning the time zone into a value object, providing some methods for juggling between the forms, and reading/writing the right versions to/from the API.

1. Creates a value object called `Timezone`
2. Converts `User::timezone` from `?string` to `?Timezone`
3. `Client::createUser()` converts `Timezone` to "Provided Name" as per SmarterU's recommendations.
4. `Client::updateUser()` converts `Timezone` to "Provided Name" as per SmarterU's recommendations.
5. `Client::getUser()` converts "display value" of time zone to `Timezone`
6. Fix issue discovered with incorrect case on some tags. It's `Timezone` not `TimeZone`.
7. Update unit tests to work with these changes
8. Added in a new `example`.  Note you can provide keys via `getenv()` which feels like I have lower risk of commiting code with secrets.

### CODE REVIEW

File: example/CreateUserLiveTest.php [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+    ->setSupervisorNotifications(true)
+    ->setTimezone(Timezone::fromProvidedName('US/Mountain'))
+    ->setAuthenticationType('External')
+    ->setPhonePrimary('555-555-5555');
+
+try {
+    // Create the Client for speaking to the API
+    $client = new Client($accountKey, $userKey);
+    
+    // Update the user
```
Comment (tomegantcs) [inline example/CreateUserLiveTest.php:48]: NIT
```suggestion
    // Create the user
```

File: example/UpdateUserLiveTest.php [hunk 2]
```diff
@@ -18,24 +18,40 @@
...
+use CBS\SmarterU\Exceptions\SmarterUException;
 
 /**
  * This script contains a live test for Client::updateUser. It was used to
  * intentionally trigger errors and see how the API responds.
  */
-$accountKey = ''; //insert key here before running
-$userKey = ''; //insert key here before running
+$accountKey = '87CD3F946F81B62242AC4B5E4DC8F59F'; //insert key here before running
+$userKey = 'st^cyxyxoj6okog69ih4is983qufylzhe8*uf8c8'; //insert key here before running
```
Comment (tomegantcs) [inline example/UpdateUserLiveTest.php:29]: Please tel me these are not your keys... Maybe use the environment variable thing you use in `example/CreateUserLiveTest.php`

Comment (brianreichtcs) [reply example/UpdateUserLiveTest.php]: I updated it to use `getenv().

File: tests/DataTypes/TimezoneTest.php [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+    public function testFromProvidedNameReturnsTimezoneForValidValue() {
+        $instance = Timezone::fromProvidedName('US/Eastern');
+
+        $this->assertInstanceOf(Timezone::class, $instance);
+        $this->assertEquals('US/Eastern', $instance->getProvidedName());
+        $this->assertEquals('(GMT-5:00) - US/Eastern', $instance->getDisplayValue());
+    }
+
+    /**
+     * Verifies taht fromDisplayValue() returns a Timezone instance for a valid
```
Comment (tomegantcs) [inline tests/DataTypes/TimezoneTest.php:111]: NIT
```suggestion
     * Verifies that fromDisplayValue() returns a Timezone instance for a valid
```

File: tests/DataTypes/TimezoneTest.php [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+     * when a valid provided name is passed.
+     *
+     * @dataProvider providedNameProvider
+     */
+    public function testGetDisplayValueFromProvidedNameReturnsMatchingDisplayValueForValidProvidedName(string $providedName) {
+        $this->assertEquals(
+            Timezone::VALID_TIMEZONES_PROVIDED_NAME_TO_DISPLAY_VALUE[$providedName],
+            Timezone::getDisplayValueFromProvidedName($providedName)
+        );
+    }
```
Comment (tomegantcs) [inline tests/DataTypes/TimezoneTest.php:52]: I am going to agree that this is probably too much... I think you are simply verifying that the constant keys match its values with these tests. Seems like a science experiment with `arrary_flip` being kept because... That said why not feed the data providers into the tests for the factory methods?

**Review by tomegantcs — APPROVED** [review]
I am not a big fan of accepting responsibility for maintaining a giant data table when a more comprehensive data table is built into PHP (see `DateTimeZone`) but the list for the API appears to not match up exactly so I think this is the solution we are stuck with.

File: example/UpdateUserLiveTest.php (hunk 2 above)
Comment (brianreichtcs) [reply example/UpdateUserLiveTest.php]: Reaching out to SmarterU to see about cycling our API keys since I screwed up so bad here.  @tomegantcs  and I had a side conversation about what else to do with this. We could replace these lines with `getenv()` as I did in a few spots now, or we could parameterize these scripts with `getopt()`.

**Comment by brianreichtcs** [comment]
> I am not a big fan of accepting responsibility for maintaining a giant data table when a more comprehensive data table is built into PHP (see DateTimeZone) but the list for the API appears to not match up exactly so I think this is the solution we are stuck with.

Yeah, the fact that I had to do this annoyed me too.  I'm glad in our application we're setting everyone to a single time zone. Otherwise, we were also going to have to create a function to map PHP time zones to SmarterU time zones, i.e. another map to manage...
