### PR TITLE
fix: resolve issue with ampersands in HomeGroup

### LINKED ISSUE #31: createUser breaks when HomeGroup has an ampersand
We found that reading a Group with an `&` in the group name it comes back correctly, but writing `<HomeGroup>` with back with the same value results in the group name being empty.  Something like this looks like the issue:

https://stackoverflow.com/questions/7146141/simplexmlelementaddchild-doesnt-seem-to-work-with-certain-strings

### PR DESCRIPTION
**Pull request by brianreichtcs**
If approved, this resolves a bug discovered in which we could not add a user to a group with an ampersand in their name.

The underlying issue is that `SimpleXML::addChild()` escapes `<` and `>` but not `&` and so we were creating malformed XML which, when rendered as text, had an empty `<HomeGroup/>`.  Note that this is a laser-focused solution on our problem but does point out that we should either add the same fix everywhere `addChild()` is called or reimplement `Client` using `DOMDocument` in the future.

Fixes #31

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -627,9 +628,11 @@ public function listGroups(ListGroupsQuery $query): array {
         $bodyAsXml = simplexml_load_string((string) $response->getBody());
 
         if ((string) $bodyAsXml->Result === 'Failed') {
+
```
Comment (tomegantcs) [inline src/Client.php:631]: NIT our style guide indicates code blocks should not start with an empty line

**Review by tomegantcs — APPROVED** [review]
Is there a reason for the changes in `src/Client.php` other than stylistic?

File: src/Client.php (hunk 1 above)
Comment (brianreichtcs) [reply src/Client.php:631]: @tomegantcs  good catch.  I think there was an interim step where where I was troubleshooting something where I added code, then removed it, and the newline got leftover as a vestigial organ of the change. I'll remove it before merge.
